### ISSUE TITLE
Standardize the predicted output

### ISSUE THREAD

**Issue by Michele971** [V-Sher/LightFm_HybridRecommenderSystem#5]
Hi,
I think that standardize the output of  `model.predict(user_x, np.arange(n_items))` could be a good idea to understand better the output. Is the score a distance?
This is one of my first experience with Machine Learning recommendation system, so let me know if I'm wrong!

**Comment by V-Sher** [comment]
@Michele971 The score can be interpreted as a similarity score, so the higher the better.

**Comment by Michele971** [comment]
Many thanks!
